-- *****************************************
-- Name: Edward Vuong
-- ID: 120246186
-- Date: Oct 5, 2018
-- Lab 05 DBS 201
-- Description: views and joins
-- *****************************************

DROP TABLE PREMB26.CUSTOMER;

CREATE TABLE PREMB26.customer (
    customer_number	CHAR(3)  PRIMARY KEY,
    last_name		CHAR(15) NOT NULL,
    first_name		CHAR(15) NOT NULL,
    street 		CHAR(15) NOT NULL, 
    city		CHAR(15) NOT NULL, 
    state		CHAR(2) NOT NULL,
    zip_code		DECIMAL(5,0) NOT NULL, 
    balance		DECIMAL(6,2) DEFAULT 0,
    credit_limit    		DECIMAL(5,0) DEFAULT 0, 
    sale_rep_number	CHAR(2) 
);

SELECT * FROM PREMB26.customer;

DROP TABLE PREMB26.SALESREP;
CREATE TABLE PREMB26.SALESREP (
    SALES_REP_NUMBER    CHAR(2) 	NOT NULL DEFAULT '' ,
    LAST_NAME 		    CHAR(15)  	NOT NULL DEFAULT '' ,
    FIRST_NAME 		    CHAR(15)    NOT NULL DEFAULT '' , 
    STREET 			    CHAR(15) 	NOT NULL DEFAULT '' ,  	
    CITY 				CHAR(15) 	NOT NULL DEFAULT '' ,  
    STATE			    CHAR(2)	    NOT NULL DEFAULT '' ,  	
    ZIP_CODE			DECIMAL(5, 0) NOT NULL DEFAULT 0 ,  	
    COMMISSION 		    DECIMAL(7, 2) NOT NULL DEFAULT 0 ,  	
    RATE 			    DECIMAL(3, 2) NOT NULL DEFAULT 0 ,  	
  CONSTRAINT PREMB26.SALESREPPK PRIMARY KEY( SALES_REP_NUMBER )
 ) ;  

CREATE TABLE PREMB26.ORDERLINE (  	
    ORDER_NUMBER		DECIMAL(5, 0) 	NOT NULL DEFAULT 0 ,  	
    PART_NUMBER 		CHAR(4) 		NOT NULL DEFAULT '' ,  	
    NUMBER_ORDERED	    DECIMAL(3, 0) 	NOT NULL DEFAULT 0 ,  	
    QUOTED_PRICE 		DECIMAL(6, 2) 	NOT NULL DEFAULT 0 ,  	
  CONSTRAINT PREMB26.ORDERLINE_PK PRIMARY KEY( ORDER_NUMBER, PART_NUMBER)
 );

CREATE TABLE PREMB26.PART (  	
    PART_NUMBER 		CHAR(4) 	    NOT NULL DEFAULT '' ,  	
    PART_DESCRIPTION 	CHAR(15) 	    NOT NULL DEFAULT '' ,  	
    ON_HAND			    DECIMAL(3, 0)   NOT NULL DEFAULT 0 ,  	
    CLASS			    CHAR(2) 	    NOT NULL DEFAULT '' ,  	
    WAREHOUSE		    DECIMAL(1, 0)   NOT NULL DEFAULT 0 ,  	
    PRICE 			    DECIMAL(6, 2)   NOT NULL DEFAULT 0 ,  	
  CONSTRAINT PREMB26.PART_PK PRIMARY KEY( PART_NUMBER ) 
  );

CREATE TABLE PREMB26.ORDERS (  	
    ORDER_NUMBER 	    DECIMAL(5, 0)   NOT NULL DEFAULT 0 ,  	
    ORDER_DATE      	DATE 	        NOT NULL DEFAULT CURRENT_DATE ,  	
    CUSTOMER_NUMBER 	CHAR(3) 	    NOT NULL DEFAULT '' ,  	
  CONSTRAINT PREMB26.ORDER_PK PRIMARY KEY( ORDER_NUMBER ) 
  );

INSERT INTO PREMB26.CUSTOMER
     SELECT * FROM PREMIERE.CUSTOMER;

INSERT INTO PREMB26.ORDERS
    SELECT * FROM PREMIERE.ORDERS;

INSERT INTO PREMB26.PART
    SELECT * FROM PREMIERE.PART;

INSERT INTO PREMB26.ORDERLINE
    SELECT * FROM PREMIERE.ORDERLINE;

INSERT INTO PREMB26.SALESREP
    SELECT * FROM PREMIERE.SALESREP;

ALTER TABLE PREMB26.ORDERLINE  	ADD CONSTRAINT PREMB26.ORDERLFK1  	FOREIGN KEY( ORDER_NUMBER )  	REFERENCES PREMB26.ORDERS ( ORDER_NUMBER ) ;  
ALTER TABLE PREMB26.ORDERLINE  	ADD CONSTRAINT PREMB26.ORDERLFK2  	FOREIGN KEY( PART_NUMBER )  		REFERENCES PREMB26.PART ( PART_NUMBER ) ;  
ALTER TABLE PREMB26.ORDERS  		ADD CONSTRAINT PREMB26.ORDERSFK1  	FOREIGN KEY( CUSTOMER_NUMBER )  	REFERENCES PREMB26.CUSTOMER ( CUSTOMER_NUMBER ) ;	  

CREATE VIEW  PREMB26.CUST_REP_VIEW AS 
    SELECT c.CUSTOMER_NUMBER,  
           c.FIRST_NAME||' '|| c.LAST_NAME as "Customer Name",
		 s.FIRST_NAME||' '||  s.LAST_NAME as "Sales Rep Name"
    FROM 	 PREMIERE.CUSTOMER c, PREMIERE.SALESREP s 
    WHERE  c.SALES_REP_NUMBER = s.SALES_REP_NUMBER;

SELECT * FROM PREMB26.cust_rep_view;

CREATE VIEW PREMB26.ORDER_INFO AS
     SELECT CUSTOMER_NUMBER, PREMB26.ORDERS.ORDER_NUMBER, PART_NUMBER, NUMBER_ORDERED, QUOTED_PRICE
    FROM PREMB26.ORDERS, PREMB26.ORDERLINE
     WHERE PREMB26.ORDERS.ORDER_NUMBER = PREMB26.ORDERLINE.ORDER_NUMBER;

SELECT * FROM PREMB26.ORDER_INFO;

CREATE VIEW PREMB26.FULL_ORDER_INFO AS
     SELECT CUSTOMER_NUMBER, PREMB26.ORDERS.ORDER_NUMBER, PART_NUMBER, NUMBER_ORDERED, QUOTED_PRICE, NUMBER_ORDERED*QUOTED_PRICE as "TOTAL"
    FROM PREMB26.ORDERS, PREMB26.ORDERLINE
     WHERE PREMB26.ORDERS.ORDER_NUMBER = PREMB26.ORDERLINE.ORDER_NUMBER;

SELECT * FROM PREMB26.FULL_ORDER_INFO;